package com.daisyworks.common.stk500;

public enum STK500Event
{
  SYNC_STARTED,
  SYNC_DONE,
  PARAMETERS_SET_START,
  PARAMETERS_SET_DONE,
  FIRMWARE_SEND_START,
  FIRMWARE_SEND_UPDATE,
  FIRMWARE_SEND_DONE,
  COMPLETE;
}
